version: "3.1"

services:
    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 3306:3306
        volumes:
            - ./mysql_data:/var/lib/mysql

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        ports:
            - 8080:8080
